### ISSUE TITLE
Allow admin to update the previously saved list of options in Wheel of Chance

### ISSUE THREAD

**Issue by nickburrett** [GamesNight/GamesNight#14]
Allow admin to update the previously saved list of options in Wheel of Chance

**Comment by GamesNight** [comment]
To confirm, but update you mean

1. Select an existing Preset
2. Chances the values
3. Save the new values against the chosen preset.

**Comment by nickburrett** [comment]
Correct

**Comment by GamesNight** [comment]
Created an action menu to group all preset related functionality in one place.
