### ISSUE TITLE
Allow admin to delete a list of previously saved options in Wheel of Chance

### ISSUE THREAD

**Issue by nickburrett** [GamesNight/GamesNight#15]
Allow admin to delete a list of previously saved options in Wheel of Chance

**Comment by GamesNight** [comment]
You should be able to do this using the Wheel option on the Preferences window.

You can also delete Horse Race presets as well from the option in Preferences.

**Comment by nickburrett** [comment]
Didn't see this, apologies!

**Comment by GamesNight** [comment]
Not a problem, probably needs some better documentation / visibility around that
