### ISSUE TITLE
Tortoise Racing (or some other comical race)

### ISSUE THREAD

**Issue by nickburrett** [GamesNight/GamesNight#17]
Popular with many people in my industry, animated tortoise racing.  Also, maybe you could consider animated "Dildo Derby" - I'll leave you to Google that one!

https://www.dropbox.com/s/lcngpdaw6yk5gcg/TortoiseRaces.mp4?dl=0

**Comment by GamesNight** [comment]
Thanks for the suggestion. Having variants of racing is on my radar, though probably sometime next year.

**Comment by GamesNight** [comment]
New runners and backgrounds in a more cartoon style have been commissioned. This also includes semi naked male and female strippers.

I'm hoping to get these out sometime in Feb/Mar
