### ISSUE TITLE
More variants

### ISSUE THREAD

**Issue by GamesNight** [GamesNight/GamesNight#8]
Are there any more popular variants of Lottery that could be provided?

There are some games that have two Bonus Balls.

**Comment by githublemming** [comment]
Lottery can now play the following variants from around the world.

* LotteryDrawType(numMainBalls: 5, maxMainBall: 50, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 5, maxMainBall: 80, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 5, maxMainBall: 39, numBonusBalls: 1, maxBonusBall: 14)
* LotteryDrawType(numMainBalls: 5, maxMainBall: 47, numBonusBalls: 1, maxBonusBall: 10)
* LotteryDrawType(numMainBalls: 5, maxMainBall: 60, numBonusBalls: 1, maxBonusBall: 4)
* LotteryDrawType(numMainBalls: 5, maxMainBall: 69, numBonusBalls: 1, maxBonusBall: 26)
* LotteryDrawType(numMainBalls: 5, maxMainBall: 70, numBonusBalls: 1, maxBonusBall: 25)
* LotteryDrawType(numMainBalls: 5, maxMainBall: 50, numBonusBalls: 2, maxBonusBall: 12)
* LotteryDrawType(numMainBalls: 5, maxMainBall: 50, numBonusBalls: 2, maxBonusBall: 10)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 45, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 47, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 49, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 52, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 59, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 60, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 75, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 90, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 59, numBonusBalls: 1, maxBonusBall: 5)

**Comment by GamesNight** [comment]
Games Night now supports the following Lottery variants from around the world.

* LotteryDrawType(numMainBalls: 5, maxMainBall: 50, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 5, maxMainBall: 80, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 5, maxMainBall: 39, numBonusBalls: 1, maxBonusBall: 14)
* LotteryDrawType(numMainBalls: 5, maxMainBall: 47, numBonusBalls: 1, maxBonusBall: 10)
* LotteryDrawType(numMainBalls: 5, maxMainBall: 60, numBonusBalls: 1, maxBonusBall: 4)
* LotteryDrawType(numMainBalls: 5, maxMainBall: 69, numBonusBalls: 1, maxBonusBall: 26)
* LotteryDrawType(numMainBalls: 5, maxMainBall: 70, numBonusBalls: 1, maxBonusBall: 25)
* LotteryDrawType(numMainBalls: 5, maxMainBall: 50, numBonusBalls: 2, maxBonusBall: 12)
* LotteryDrawType(numMainBalls: 5, maxMainBall: 50, numBonusBalls: 2, maxBonusBall: 10)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 45, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 47, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 49, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 52, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 59, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 60, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 75, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 90, numBonusBalls: 0, maxBonusBall: 0)
* LotteryDrawType(numMainBalls: 6, maxMainBall: 59, numBonusBalls: 1, maxBonusBall: 5)
